# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: be60b67d3ea0e981a6b9e61e6b76062b7233e905d35cc2018c8301c8acb9cac027ae1b9a592f45f6642274d8c5e674536a65face94df1c13a6a11a6d31d6b56d

test:
  secret_key_base: 07951944a74868875a1966e100a6ce6581abe841d245869dee3573ddb3345b19e30680859fef6bacd93365066ea3eb35c68f73c313e78b1b38d5780b1da9c85a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
